github.com:
    users:
        yeshrajgupta63-dev:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: yeshrajgupta63-dev
